INSERT INTO cito_wordbanks (word, grade, category, rule, difficulty, source) VALUES
('kat', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('hond', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('huis', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('boom', 3, 'basic', 'Verdubbeling: oo', 1, 'SLO'),
('zon', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('maan', 3, 'basic', 'Verdubbeling: aa', 1, 'SLO'),
('auto', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('fiets', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('school', 3, 'basic', 'Verdubbeling: oo', 1, 'SLO'),
('boot', 3, 'basic', 'Verdubbeling: oo', 1, 'SLO'),
('dag', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('nacht', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('hand', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('voet', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('neus', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('oor', 3, 'basic', 'Verdubbeling: oo', 1, 'SLO'),
('mond', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('rood', 3, 'basic', 'Verdubbeling: oo', 1, 'SLO'),
('blauw', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('geel', 3, 'basic', 'Verdubbeling: ee', 1, 'SLO'),
('groen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('wit', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('zwart', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('groot', 3, 'basic', 'Verdubbeling: oo', 1, 'SLO'),
('klein', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('lang', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('kort', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('eten', 3, 'basic', 'Verdubbeling: ee', 1, 'SLO'),
('drinken', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('slapen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('spelen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('werken', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('leren', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('gaan', 3, 'basic', 'Verdubbeling: aa', 1, 'SLO'),
('komen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('zitten', 3, 'basic', 'Verdubbeling: tt', 1, 'SLO'),
('staan', 3, 'basic', 'Verdubbeling: aa', 1, 'SLO'),
('lopen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('rennen', 3, 'basic', 'Verdubbeling: nn', 1, 'SLO'),
('vallen', 3, 'basic', 'Verdubbeling: ll', 1, 'SLO'),
('bouwen', 3, 'basic', 'Gewoon woord (ou)', 1, 'SLO'),
('tekenen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('schrijven', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('lezen', 3, 'basic', 'Gewoon woord (ez)', 1, 'SLO'),
('tellen', 3, 'basic', 'Verdubbeling: ll', 1, 'SLO'),
('zingen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('dansen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('katten', 3, 'basic', 'Verdubbeling: tt', 1, 'SLO'),
('honden', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('huizen', 3, 'basic', 'Gewoon woord, z-regel', 1, 'SLO'),
('bomen', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('boten', 3, 'basic', 'Gewoon woord', 1, 'SLO'),
('aarde', 4, 'verdubbeling-aa', 'aa in aarde', 2, 'SLO'),
('appel', 4, 'verdubbeling', 'Verdubbeling: pp', 2, 'SLO'),
('baas', 4, 'verdubbeling-aa', 'aa in baas', 2, 'SLO'),
('bal', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('ballen', 4, 'verdubbeling', 'Verdubbeling: ll', 2, 'SLO'),
('band', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('bank', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('bed', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('been', 4, 'verdubbeling-ee', 'ee in been', 2, 'SLO'),
('berg', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('beurt', 4, 'basic', 'Gewoon woord (eu)', 1, 'SLO'),
('beweging', 4, 'ei-ij', 'ei voor ei-ij regel', 2, 'SLO'),
('bezem', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('bijna', 4, 'ei-ij', 'ij in bijna', 2, 'SLO'),
('blaar', 4, 'verdubbeling-aa', 'aa in blaar', 2, 'SLO'),
('blauw', 4, 'basic', 'Gewoon woord (au)', 1, 'SLO'),
('bliksem', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('bloed', 4, 'verdubbeling-oe', 'oe in bloed', 2, 'SLO'),
('bloem', 4, 'verdubbeling-oe', 'oe in bloem', 2, 'SLO'),
('blok', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('blokkade', 4, 'verdubbeling', 'Verdubbeling: kk', 2, 'SLO'),
('blouse', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('buis', 4, 'ei-ij', 'ui voor ui-regel', 2, 'SLO'),
('boek', 4, 'verdubbeling-oe', 'oe in boek', 2, 'SLO'),
('boog', 4, 'verdubbeling-oo', 'oo in boog', 2, 'SLO'),
('boom', 4, 'verdubbeling-oo', 'oo in boom', 2, 'SLO'),
('boot', 4, 'verdubbeling-oo', 'oo in boot', 2, 'SLO'),
('borst', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('bos', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('boter', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('bouw', 4, 'basic', 'Gewoon woord (ou)', 1, 'SLO'),
('bouwland', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('bovenkant', 4, 'basic', 'Samengesteld woord', 2, 'SLO'),
('boven', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('braad', 4, 'verdubbeling-aa', 'aa in braad', 2, 'SLO'),
('bracht', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('brand', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('brandweer', 4, 'verdubbeling-ee', 'Samengesteld + ee', 3, 'SLO'),
('brood', 4, 'verdubbeling-oo', 'oo in brood', 2, 'SLO'),
('brug', 4, 'basic', 'Gewoon woord', 1, 'SLO'),
('bruid', 4, 'ei-ij', 'ui voor ui-regel', 2, 'SLO'),
('bruik', 4, 'ei-ij', 'ui in bruik', 2, 'SLO'),
('bruine', 4, 'ei-ij', 'ui + e', 2, 'SLO'),
('brutaal', 4, 'verdubbeling-aa', 'aa + t', 2, 'SLO'),
('druif', 4, 'ei-ij', 'ui in druif', 2, 'SLO'),
('duin', 4, 'ei-ij', 'ui in duin', 2, 'SLO'),
('duizend', 4, 'ei-ij', 'ui in duizend', 2, 'SLO'),
('tijdens', 4, 'ei-ij', 'ij in tijdens', 2, 'SLO'),
('tuin', 4, 'ei-ij', 'ui in tuin', 2, 'SLO'),
('veilig', 4, 'ei-ij', 'ei in veilig', 2, 'SLO'),
('vein', 4, 'ei-ij', 'ei in vein', 2, 'SLO'),
('veining', 4, 'ei-ij', 'ei + ing', 2, 'SLO'),
('vijf', 4, 'ei-ij', 'ij in vijf', 2, 'SLO'),
('zijn', 4, 'ei-ij', 'ij in zijn', 2, 'SLO'),
('zuivel', 4, 'ei-ij', 'ui + vel', 2, 'SLO'),
('zwijn', 4, 'ei-ij', 'ij in zwijn (varken)', 2, 'SLO'),
('wijl', 4, 'ei-ij', 'ij in wijl', 2, 'SLO'),
('wijd', 4, 'ei-ij', 'ij in wijd', 2, 'SLO'),
('wijkagent', 4, 'ei-ij', 'ij samengesteld', 3, 'SLO'),
('wijsheid', 4, 'ei-ij', 'ij + heid', 3, 'SLO'),
('wijs', 4, 'ei-ij', 'ij in wijs (wijze)', 2, 'SLO'),
('wijn', 4, 'ei-ij', 'ij in wijn', 2, 'SLO'),
('keizer', 4, 'ei-ij', 'ei in keizer', 2, 'SLO'),
('ij', 4, 'ei-ij', 'ij = waterweg', 2, 'SLO'),
('rijst', 5, 'ei-ij', 'ij in rijst', 2, 'SLO'),
('fijn', 5, 'ei-ij', 'ij in fijn', 2, 'SLO'),
('beige', 5, 'ei-ij', 'ei in beige', 2, 'SLO'),
('trein', 5, 'ei-ij', 'ei in trein', 2, 'SLO'),
('klein', 5, 'ei-ij', 'ei in klein', 2, 'SLO'),
('vrouw', 5, 'au-ou', 'ou in vrouw', 2, 'SLO'),
('grau', 5, 'au-ou', 'au in grau', 2, 'SLO'),
('flauw', 5, 'au-ou', 'au in flauw', 2, 'SLO'),
('betaald', 6, 'dt-regel', 'Werkwoord: betaal + d', 3, 'SLO'),
('gezegd', 6, 'dt-regel', 'Werkwoord: zeg + d', 3, 'SLO'),
('gekocht', 6, 'dt-regel', 'Werkwoord: koop + t', 3, 'SLO'),
('zeeën', 6, 'trema', 'zee + ën (trema)', 3, 'SLO'),
('ideeën', 6, 'trema', 'idee + ën (trema)', 3, 'SLO'),
('werkt', 7, 'werkwoord-stam', 'werk + t', 3, 'SLO'),
('fietst', 7, 'werkwoord-stam', 'fiets + t', 3, 'SLO'),
('rijdt', 7, 'werkwoord-stam', 'rijd + t', 3, 'SLO'),
('wordt', 7, 'werkwoord-stam', 'word + t', 3, 'SLO'),
('vindt', 7, 'werkwoord-stam', 'vind + t', 3, 'SLO'),
('gelopen', 8, 'voltooid-deelwoord', 'ge + lopen', 4, 'SLO'),
('gespeeld', 8, 'voltooid-deelwoord', 'ge + speel + d', 4, 'SLO'),
('gereden', 8, 'voltooid-deelwoord', 'ge + reden', 4, 'SLO'),
('gewerkt', 8, 'voltooid-deelwoord', 'ge + werk + t', 4, 'SLO'),
('bibliotheek', 8, 'samengesteld', 'bibliotheek word', 4, 'SLO'),
('schoolbord', 8, 'samengesteld', 'school + bord', 4, 'SLO'),
('lopen', 3, 'werkwoord', 'Regelmatig werkwoord', 1, 'AI-generated'),
('spelen', 3, 'werkwoord', 'Regelmatig werkwoord', 1, 'AI-generated'),
('maken', 3, 'werkwoord', 'Regelmatig werkwoord', 1, 'AI-generated'),
('eten', 3, 'werkwoord', 'Regelmatig werkwoord', 1, 'AI-generated'),
('drinken', 3, 'werkwoord', 'Regelmatig werkwoord', 1, 'AI-generated'),
('slapen', 3, 'werkwoord', 'Regelmatig werkwoord', 1, 'AI-generated'),
('werken', 4, 'werkwoord', 'Regelmatig werkwoord', 2, 'AI-generated'),
('fietsen', 4, 'werkwoord', 'Regelmatig werkwoord', 2, 'AI-generated'),
('schrijven', 4, 'werkwoord', 'Regelmatig werkwoord', 2, 'AI-generated'),
('lezen', 4, 'werkwoord', 'Regelmatig werkwoord', 2, 'AI-generated'),
('antwoorden', 5, 'werkwoord', 'Regelmatig werkwoord', 2, 'AI-generated'),
('antwoorden', 5, 'werkwoord', 'Regelmatig werkwoord', 2, 'AI-generated'),
('bereiken', 5, 'werkwoord', 'Regelmatig werkwoord', 2, 'AI-generated'),
('bepalen', 5, 'werkwoord', 'Regelmatig werkwoord', 2, 'AI-generated'),
('kiezen', 6, 'werkwoord', 'Sterk werkwoord', 3, 'AI-generated'),
('zingen', 6, 'werkwoord', 'Sterk werkwoord', 3, 'AI-generated'),
('dragen', 6, 'werkwoord', 'Sterk werkwoord', 3, 'AI-generated'),
('groeien', 7, 'werkwoord', 'Regelmatig werkwoord', 3, 'AI-generated'),
('gebeuren', 7, 'werkwoord', 'Regelmatig werkwoord', 3, 'AI-generated'),
('begreipen', 8, 'werkwoord', 'Sterk werkwoord', 4, 'AI-generated'),
('verdienen', 8, 'werkwoord', 'Regelmatig werkwoord', 4, 'AI-generated')
ON CONFLICT (word) DO NOTHING;